### ISSUE TITLE
Clean code, TDD, and software architecture in Jupyter notebooks

### ISSUE THREAD

**Issue by guillaume-chevalier** [NirantK/best-of-jupyter#2]
Hi @NirantK, 

You asked for tests at https://github.com/keon/awesome-nlp/pull/147

So you gave me the idea to write this article on how to do Clean code, TDD, and grow software architecture out of Jupyter notebooks: https://github.com/guillaume-chevalier/How-to-grow-neat-software-architecture-out-of-jupyter-notebooks

And now I find this repository of yours: "best-of-jupyter". What a coincidence! Well... you may enjoy this read. 

Best Regards, 
Guillaume

**Comment by NirantK** [comment]
That is nice. Very conversational! 

Thanks for sharing @guillaume-chevalier !

**Comment by guillaume-chevalier** [comment]
@NirantK Hey, it turns out I found that my post just got featured on the [HackerNews](https://news.ycombinator.com/item?id=18661303)'s 1st page

**Comment by NirantK** [comment]
Oh wow. This is fantastic. Good discussion on the post as well :)
